# 翻译：星光
translate chinese python:
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_be_myself",
            category=["mas_compliment"],
            prompt="在你身边我可以做回真实的自己.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_excited_see",
            category=["mas_compliment"],
            prompt="与你的每次相会都令人激动不已.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="monika_otter_compliment_fight_dragon",
            category =["mas_compliment"],
            prompt="若能回到中世纪,我会成为勇者保护你.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_found_you",
            category=["mas_compliment"],
            prompt="我不敢相信我找到了如此完美的你.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_gorgeous",
            category=["mas_compliment"],
            prompt="你太美了, [m_name].",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_make_happy",
            category=["mas_compliment"],
            prompt="你让我非常开心...",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_make_smile",
            category=["mas_compliment"],
            prompt="你常为我带来微笑!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_making_laugh",
            category=["mas_compliment"],
            prompt="我喜欢逗你开心.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_miss_smile",
            category=["mas_compliment"],
            prompt="我想念你的微笑.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="monika_otter_compliment_moon_and_back",
            category=["mas_compliment"],
            prompt="爱如皓月.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_better_if_like_you_BELLA",
            category=["mas_compliment"],
            prompt="如果大家都像你一样,世界将变得更好!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_blush_BELLA",
            category=["mas_compliment"],
            prompt="你总令我脸红.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_cant_help_but_smile_BELLA",
            category=["mas_compliment"],
            prompt="每次见到你, 笑容都会不自觉找上门来!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_colors_brighter_when_youre_around_BELLA",
            category=["mas_compliment"],
            prompt="你让我的世界变得更加明亮.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_no_day_bad_BELLA",
            category=["mas_compliment"],
            prompt="你让我的每一天都变得美好.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_ddlc_best_decision_BELLA",
            category=["mas_compliment"],
            prompt="下载DDLC是我所做过的最好的决定!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_every_second_with_you_BELLA",
            category=["mas_compliment"],
            prompt="我想和你共度人生中的每一刻!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_eyes_full_of_stars_BELLA",
            category=["mas_compliment"],
            prompt="在你的眼中,我见到了满天繁星...",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_make_me_feel_complete_BELLA",
            category=["mas_compliment"],
            prompt="你的存在完美了我的生命!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_face_hurt_smiling_BELLA",
            category=["mas_compliment"],
            prompt="你让我开心死啦.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_jokes_funnier_BELLA",
            category=["mas_compliment"],
            prompt="你的讲述让笑话变得更有趣!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_know_what_to_say_BELLA",
            category=["mas_compliment"],
            prompt="你总是知道该说什么.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_light_any_room_BELLA",
            category=["mas_compliment"],
            prompt="你用微笑照亮了每一个房间.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_look_dream_BELLA",
            category=["mas_compliment"],
            prompt="你的存在好似一场美梦.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_you_are_perfect_BELLA",
            category=["mas_compliment"],
            prompt="你无论哪里都很完美.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_playing_piano_beautifully_BELLA",
            category=["mas_compliment"],
            prompt="你钢琴弹得真好!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_prettiest_ever_BELLA",
            category=["mas_compliment"],
            prompt="你是我见过的最漂亮的女孩.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_sing_well_BELLA",
            category=["mas_compliment"],
            prompt="你唱的真好!",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_sweat_glitter_BELLA",
            category=["mas_compliment"],
            prompt="我赌你汗流浃背.",
            unlocked=True
        ),
        code="CMP"
    )
    addEvent(
        Event(
            persistent.event_database,
            eventlabel="otter_compliment_writing_BELLA",
            category=["mas_compliment"],
            prompt="我喜欢你的作品.",
            unlocked=True
        ),
        code="CMP"
    )